from app.dependency import get_current_user
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from datetime import date
from sqlmodel.ext.asyncio.session import AsyncSession
from app.database import get_session
from app.service.doctors_visit_service import (
    save_doctors_visit_to_db,
    get_doctors_visits_from_db,
    update_doctors_visit_in_db,
    delete_doctors_visit_in_db,
    get_doctors_visits_list
)
from app.models.user import User


router = APIRouter(prefix="/doctors-visits")

# we will create a new model for doctors visit that will be used in the request body when creating a new doctors visit. This model will be different from the DoctorsVisit model because we don't want to include id and created_at in the request body when creating a new doctors visit. These fields will be automatically generated by the database.
class DoctorsVisitCreate(BaseModel):
    family_member_id: int
    doctor_name: str
    hospital_name: str
    visit_date: date
    diagnosis: str | None = None
    prescription_notes: str | None = None
    follow_up_date: date | None = None  


@router.post("/create")
async def create_doctors_visit(data: DoctorsVisitCreate, current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    user_id = current_user.id
    new_doctors_visit = await save_doctors_visit_to_db(user_id, data, session)
    return new_doctors_visit    

@router.get("/get_all")
async def get_doctors_visits(current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    user_id = current_user.id
    doctors_visits = await get_doctors_visits_from_db(user_id, session)
    return {"doctors_visits": doctors_visits}

@router.put("/{visit_id}")
async def update_doctors_visit(visit_id: int, data: DoctorsVisitCreate, current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    user_id = current_user.id
    updated_doctors_visit = await update_doctors_visit_in_db(visit_id, data, user_id, session)
    return updated_doctors_visit

@router.put("/{visit_id}/delete")
async def delete_doctors_visit(visit_id: int, current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    user_id = current_user.id
    deleted_doctors_visit = await delete_doctors_visit_in_db(visit_id, user_id, session)
    return deleted_doctors_visit


@router.get("/")
async def list_doctors_visits(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
    family_member_id: int | None = None,
    doctor_name: str | None = None,
    visit_date: date | None = None,
    start_date: date | None = None,
    end_date: date | None = None,
    page: int = 1,
    page_size: int = 10,
    sort_by: str = "visit_date",
    sort_order: str = "desc"
):
    result = await get_doctors_visits_list(
        current_user.id,
        session,
        family_member_id,
        doctor_name,
        visit_date,
        start_date,
        end_date,
        page,
        page_size,
        sort_by,
        sort_order
    )
    return result