from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlmodel.ext.asyncio.session import AsyncSession
from app.database import get_session
from app.service.health_record_service import save_health_record_to_db , delete_health_record_db, update_health_record_db ,get_health_record_db 
from app.models.user import User
from app.dependency import get_current_user
from app.models.health_record import HealthRecord

router = APIRouter(prefix="/health_records")

class HealthRecordCreate(BaseModel):
    family_member_id: int
    blood_pressure: str | None = None
    heart_rate: int | None = None
    weight: float | None = None
    body_temperature: float | None = None
    sugar_level: float | None = None
    note: str | None = None
    #  different from the HealthRecord model because we don't want to include id and created_at in the request body when creating a new health record. These fields will be automatically generated by the database.

# @router.post("/", response_model=HealthRecord)

# response_model=HealthRecord means that the response will be validated against the HealthRecord model and will be returned in that format.
# similar to class HealthRecordCreate(BaseModel) but here we are using the actual SQLModel model because we want to return the created health record with all its fields including id and created_at.

@router.post("/")
async def create_health_record(data: HealthRecordCreate, current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)): 
   new_health_record = await save_health_record_to_db(data, current_user.id, session)
   return new_health_record


@router.get("/{health_record_id}")
async def get_health_record(health_record_id: int, current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    health_record = await get_health_record_db(health_record_id, current_user.id, session)
    return health_record

@router.put("/{health_record_id}")
async def update_health_record(health_record_id: int, data: HealthRecordCreate, current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    updated_health_record = await update_health_record_db(health_record_id, data, current_user.id, session)
    return updated_health_record

@router.put("/{health_record_id}/delete")
async def delete_health_record(health_record_id: int, current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    await delete_health_record_db(health_record_id, current_user.id, session)
    return {"message": "Health record deleted successfully"}
